StoreFront/StoreFront.UI.MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StoreFront.DATA.EF.Models;
using System.Data;
using System.Drawing.Printing;
using Microsoft.AspNetCore.Authorization;
using GadgetStore.UI.MVC.Utilities;
using System.Drawing;
using X.PagedList;
using X.PagedList.Mvc.Core;

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly StoreFrontContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductsController(StoreFrontContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        [AllowAnonymous]
        // GET: Products
        public async Task<IActionResult> Index()
        {
            //var storeFrontContext = _context.Products.Include(p => p.Category).Include(p => p.ProductStatus);
            var products =
                _context.Products.Where(p => p.UnitsInStock > 0 && p.ProductPrice > 3)//SELECT * FROM Products WHERE UnitsInStock > 0 and Price > $3
                .Include(p => p.Category)//similar to a JOIN on the Category table
                .Include(p => p.OrderProducts);//similar to a JOIN on the OrderProducts table



            return View(await products.ToListAsync());
        }




        [AllowAnonymous]
        public async Task<IActionResult> TiledProducts(string searchTerm, int categoryId = 0, int page = 1)
        {
            int pageSize = 6;

            var products =
               _context.Products.Where(p => p.UnitsInStock > 0)//SELECT * FROM Products WHERE Discontinued != true
               .Include(p => p.Category)//similar to a JOIN on the Category table
               .Include(p => p.OrderProducts).ToList();//similar to a JOIN on the OrderProducts table

            #region Optional Category Filter

            //Create a VIewData object to send a list of categories to the view
            //This is similar to what gets scaffolded in Products/Create()
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewBag.Category = 0;

            //At this point we need to add int categoryId as a parameter to the TiledProducts() Action
            if (categoryId != 0)
            {
                products = products.Where(p => p.CategoryId == categoryId).ToList();
                ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", categoryId);
                ViewBag.Category = categoryId;



            }


            #endregion

            #region Optional Search Filter

            if (!String.IsNullOrEmpty(searchTerm))
            {
                //In these scopes, there *is* a search term
                products = products.Where(p =>
                p.ProductName.ToLower().Contains(searchTerm.ToLower()) ||
                p.Category.CategoryName.ToLower().Contains(searchTerm.ToLower()) ||
                p.ProductDescript.ToLower().Contains(searchTerm.ToLower())).ToList();

                //ViewBag for total # of results
                ViewBag.NbrResults = products.Count;
                //ViewBag to repeat the user's search term back to them
                ViewBag.SearchTerm = searchTerm;
            }
            else
            {
                ViewBag.NbrResults = null;
                ViewBag.SearchTerm = null;
            }

            #endregion

            return View(products.ToPagedList(page, pageSize));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Discontinued()
        {
            var products = _context.Products.Where(p => p.UnitsInStock == 0)
                .Include(p => p.Category)
                .Include(p => p.OrderProducts);

            return View(await products.ToListAsync());
            //To create the view, right-click the Action -> View (Choose List Template)
        }




        [AllowAnonymous]
        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.ProductStatus)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewData["ProductStatusId"] = new SelectList(_context.ProductStatuses, "ProductStatusId", "ProductStatusName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductPrice,ProductDescript,UnitsInStock,CategoryId,ProductStatusId,ProductImage,Image")] Product product)
        {
            if (ModelState.IsValid)
            {

                if (product.Image != null)
                {
                    string ext = Path.GetExtension(product.Image.FileName);

                    string[] validExts = { ".jpg", ".jpeg", ".gif", ".png" };

                    if (validExts.Contains(ext.ToLower()) && product.Image.Length < 4_194_303)
                    {
               
                        product.ProductImage = Guid.NewGuid() + ext;

                        string webRootPath = _webHostEnvironment.WebRootPath;
                       
                        string fullImagePath = webRootPath + "/images/";

                       
                        using (var memoryStream = new MemoryStream())
                        {
                            await product.Image.CopyToAsync(memoryStream);
                            using (var img = Image.FromStream(memoryStream))
                            {
                               
                                int maxImageSize = 500;
                                int maxThumbSize = 100;

                            ImageUtility.ResizeImage(fullImagePath, product.ProductImage, img, maxImageSize, maxThumbSize);
                                
                            }
                        }
                    }
                }
                else
                {
                    product.ProductImage = "noimage.png";
                }












                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["ProductStatusId"] = new SelectList(_context.ProductStatuses, "ProductStatusId", "ProductStatusName", product.ProductStatusId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["ProductStatusId"] = new SelectList(_context.ProductStatuses, "ProductStatusId", "ProductStatusName", product.ProductStatusId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ProductPrice,ProductDescript,UnitsInStock,CategoryId,ProductStatusId,ProductImage,Image")] Product product)
        {
            #region File Upload - EDIT

           
            string oldImageName = product.ProductImage;

  
            if (product.Image != null)
            {
                
                string ext = Path.GetExtension(product.Image.FileName);

                string[] validExts = { ".jpg", ".jpeg", ".gif", ".png" };

            
                if (validExts.Contains(ext.ToLower()) && product.Image.Length < 4_194_303)
                {
              
                    product.ProductImage = Guid.NewGuid() + ext;
             
                    string webRootPath = _webHostEnvironment.WebRootPath;
                    string fullPath = webRootPath + "/images/";

                
                    if (oldImageName != "noimage.png")
                    {
                        ImageUtility.Delete(fullPath, oldImageName);
                    }

               
                    using (var memoryStream = new MemoryStream())
                    {
                        await product.Image.CopyToAsync(memoryStream);
                        using (var img = Image.FromStream(memoryStream))
                        {
                            int maxImageSize = 500;
                            int maxThumbSize = 100;

StoreFront/StoreFront.UI.MVC/Controllers/ShoppingCartController.cs
using StoreFront.DATA.EF.Models;//Added for access to the DB Context
using Microsoft.AspNetCore.Identity;//Added for access to the UserManager
using StoreFront.UI.MVC.Models;//Added for access to the CartItemViewModel
using Newtonsoft.Json;//Added for easier management of the shopping cart

using Microsoft.AspNetCore.Mvc;

namespace StoreFront.UI.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        //Fields
        private readonly StoreFrontContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        //Constructor
        public ShoppingCartController(StoreFrontContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var sessionCart = HttpContext.Session.GetString("cart");

            
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            
            if (sessionCart == null || sessionCart.Count() == 0)
            {
                
                shoppingCart = new Dictionary<int, CartItemViewModel>();

                ViewBag.Message = "There are no items in your cart.";
            }
            else
            {
                ViewBag.Message = null;
                shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);
            }

            return View(shoppingCart);
        }

        public IActionResult AddToCart(int id)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = null;


            var sessionCart = HttpContext.Session.GetString("cart");

            if (String.IsNullOrEmpty(sessionCart))
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }
            else
            {
                shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);
            }

            

            Product product = _context.Products.Find(id);

            
            CartItemViewModel civm = new CartItemViewModel(1, product);

            
            if (shoppingCart.ContainsKey(product.ProductId)) {
           
                shoppingCart[product.ProductId].Qty++;
            }
            else
            {
                shoppingCart.Add(product.ProductId, civm);
            }

            
            string jsonCart = JsonConvert.SerializeObject(shoppingCart);
            HttpContext.Session.SetString("cart", jsonCart);

            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(int id)
        {
            var sessionCart = HttpContext.Session.GetString("cart");
            Dictionary<int, CartItemViewModel> shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);
            shoppingCart.Remove(id);
            if(shoppingCart.Count == 0) 
            {
                HttpContext.Session.Remove("cart");
            }
            else
            {
                string jsonCart = JsonConvert.SerializeObject(shoppingCart);
                HttpContext.Session.SetString("cart", jsonCart);
            }
            
            return RedirectToAction("Index");
        }


        public IActionResult UpdateCart(int productId, int qty)
        {
            //Retrieve the cart from session storage
            var sessionCart = HttpContext.Session.GetString("cart");

            //Deserialize from JSON to C#
            Dictionary<int, CartItemViewModel> shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);

            //update the qty for our specific dictionary key
            shoppingCart[productId].Qty = qty;

            //update the JSON string stored in session with the new Qty, then return user to Index action
            string jsonCart = JsonConvert.SerializeObject(shoppingCart);
            HttpContext.Session.SetString("cart", jsonCart);
            return RedirectToAction("Index");

        }


        public async Task<IActionResult> SubmitOrder() 
        {
            string? userId = (await _userManager.GetUserAsync(HttpContext.User))?.Id;
            CustomerDetail cd = _context.CustomerDetails.Find(userId);
            Order o = new Order()
            {
                CustomerId = userId,
                OrderDate = DateTime.Now,
                ShipToName = cd.FirstName + " " + cd.LastName,
                ShipCity = cd.City,
                ShipState = cd.State,
                ShipZip = cd.Zip
            };

            _context.Orders.Add(o);

            var sessionCart = HttpContext.Session.GetString("cart");

            Dictionary<int, CartItemViewModel> shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);

            foreach (var item in shoppingCart)
            {
                OrderProduct op = new OrderProduct()
                {
                    OrderId = o.OrderId,
                    ProductId = item.Key,
                    ProductPrice = item.Value.Product.ProductPrice,
                    Quantity = (short)item.Value.Qty
                };

                o.OrderProducts.Add(op);

            }

            //Commit our changes to the DB
            _context.SaveChanges();
            return RedirectToAction("Index", "Orders");
        }
    }
}

StoreFront/StoreFront.UI.MVC/Views/ShoppingCart/Index.cshtml
@model Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel>

@{
    ViewData["Title"] = "Cart";
    decimal? cartTotal = 0;
}

<!-- Shop Cart Section Begin -->
<section class="shop-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                @if(Model.Count == 0){
                <p class="alert alert-warning text-center">
                    @ViewBag.Message
                </p>
                }
                else
                {
                <div class="shop__cart__table">
                    <table class="table table-striped table-hover mx-2">
                        <thead class="text-center">
                            <tr>
                                <th>Image</th> @* th = table header*@
                                <th>Quantity</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Total</th>
                                <th></th> @* Left empty for actions *@
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                                {  
                                <tr class="text-center">
                                    <td class="cart__product__item">
                                         <img src="~/images/t_@item.Value.Product.ProductImage" alt="@item.Value.Product.ProductName" />
                                    </td>
                                    <td class="cart__quantity">
                                        <div class="pro-qty">
                                            <form asp-action="UpdateCart">
                                                <input type="hidden" name="productId" value="@item.Key" />
                                                <input type="text" name="qty" value="@item.Value.Qty"
                                                        class="form-control d-block mx-auto text-center w-50" />
                                                <input type="submit" value="Update Cart" class="btn btn-primary btn-sm" />
                                            </form>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="cart__product__item__title">
                                            <h6>@item.Value.Product.ProductName</h6>
                                        </div>
                                    </td>
                                    <td class="cart__price">@Html.DisplayFor(modelItem => item.Value.Product.ProductPrice)</td>
                                     <td class="cart__total">
                                            @{
                                                decimal? lineTotal = item.Value.Qty * item.Value.Product.ProductPrice;//total for 1 line item
                                            }
                                            @string.Format($"{lineTotal:c}")
                                     </td>
                                    <td><a asp-action="RemoveFromCart" asp-controller="ShoppingCart" asp-route-id="@item.Key" class="btn btn-danger mx-5">Remove From Cart</a></td>
                            </tr>
                                }
                        </tbody>
                    </table>
                </div>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="cart__btn">
                    <a href="@Url.Action("Index", "Products")">Continue Shopping</a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="cart__btn update__btn">
                    <a href="#"><span class="icon_loading"></span> Update cart</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="discount__content">
                    <h6>Discount codes</h6>
                    <form action="#">
                        <input type="text" placeholder="Enter your coupon code">
                        <button type="submit" class="site-btn">Apply</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-2">
                <div class="cart__total__procced">
                    <h6>Cart total</h6>
                    <ul>
                        <li>Subtotal
                            <span>
                            @string.Format($"{cartTotal:c}")
                            </span>
                        </li>
                        <li>Total <span>@string.Format($"{cartTotal:c}")</span></li>
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <p>
                            <a asp-action="SubmitOrder" class="btn btn-success">
                                Submit Order
                            </a>
                        </p>
                    }
                    else
                    {
                        <p>
                            To place this order, you must be logged in
                        </p>
                        <a asp-area="Identity" asp-page="/Account/Login" class=" btn btn-primary">Login</a>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shop Cart Section End -->